name: Print Python Version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Print Python version
        run: python --version
